In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 3.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.5 MB 3.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.5 MB 7.3 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.5 MB 9.5 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.5 MB 9.6 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.5 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 8.8 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)

array([[ 1.86942562, -0.82157425],
       [-1.49320223,  0.56515503],
       [ 0.22824381, -1.7383844 ]])

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [5]:
# Basic Math
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [7]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]

# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr >3
arr[mask]

array([4, 5])

In [8]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)

# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

# Stacking
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [15]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]


array([6, 7, 8])

In [14]:
# Save to a file
np.save('array.npy', arr)

# Load from a file
loaded_arr = np.load('array.npy')

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B


In [16]:
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [17]:
np.vstack((a, b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [18]:
np.hstack((a, b))

array([1, 2, 3, 3, 4])