In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])

In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.random.rand(3, 2)

array([[0.51222733, 0.91256987],
       [0.02660774, 0.97532285],
       [0.60898985, 0.84624597]])

In [12]:
np.random.randn(3, 2)

array([[-0.48957629, -0.33175874],
       [-0.73244571,  1.8777824 ],
       [-1.34773187,  1.50355851]])

In [13]:
np.random.randn(3, 2)

array([[-0.83839595,  0.19909009],
       [-0.09539621, -1.32940295],
       [ 1.1691256 ,  1.43806622]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
print(arr.shape)

(2, 3)


In [16]:
print(arr.ndim)

2


In [17]:
print(arr.size)

6


In [18]:
print(arr.dtype)

int64


In [19]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [20]:
a + b

array([5, 7, 9])

In [21]:
a * b

array([ 4, 10, 18])

In [22]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [24]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [25]:
A @ B

array([[19, 22],
       [43, 50]])

In [26]:
arr = np.array([1, 2, 3, 4])

In [27]:
arr.sum()

np.int64(10)

In [28]:
arr.mean()

np.float64(2.5)

In [29]:
arr.max()

np.int64(4)

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.std()

np.float64(1.118033988749895)

In [32]:
arr = np.array([1, 2, 3, 4, 5])


In [33]:
arr[0]

np.int64(1)

In [34]:
arr[1:4]

array([2, 3, 4])

In [35]:
arr[::2]

array([1, 3, 5])

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
arr[0, 1]


np.int64(2)

In [38]:
arr[:, 1]

array([2, 5])

In [39]:
arr[1, :2]

array([4, 5])